# Generated by Django 5.2.7 on 2025-10-12 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhan_vien', models.CharField(max_length=10, unique=True, verbose_name='Mã nhân viên')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('ngay_sinh', models.DateField(verbose_name='Ngày sinh')),
                ('phong_ban', models.CharField(max_length=100, verbose_name='Phòng ban')),
                ('chuc_vu', models.CharField(max_length=100, verbose_name='Chức vụ')),
                ('ngay_vao_lam', models.DateField(verbose_name='Ngày vào làm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Nhân Viên',
                'verbose_name_plural': 'Danh sách Nhân Viên',
            },
        ),
    ]
