# Generated by Django 5.2.7 on 2025-10-12 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhan_vien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChucVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_chuc_vu', models.CharField(max_length=100, unique=True, verbose_name='Tên chức vụ')),
            ],
        ),
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phong_ban', models.CharField(max_length=100, unique=True, verbose_name='Tên phòng ban')),
            ],
        ),
        migrations.CreateModel(
            name='ChamCong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField(verbose_name='Ngày chấm công')),
                ('gio_vao', models.TimeField(verbose_name='Giờ vào')),
                ('gio_ra', models.TimeField(blank=True, null=True, verbose_name='Giờ ra')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhan_vien.nhanvien', verbose_name='Nhân viên')),
            ],
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='chuc_vu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhan_vien.chucvu', verbose_name='Chức vụ'),
        ),
        migrations.CreateModel(
            name='DonXinNghi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_bat_dau', models.DateField(verbose_name='Ngày bắt đầu nghỉ')),
                ('ngay_ket_thuc', models.DateField(verbose_name='Ngày kết thúc')),
                ('ly_do', models.TextField(verbose_name='Lý do')),
                ('trang_thai', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=10, verbose_name='Trạng thái')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhan_vien.nhanvien', verbose_name='Nhân viên')),
            ],
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='phong_ban',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhan_vien.phongban', verbose_name='Phòng ban'),
        ),
    ]
