# Generated by Django 5.2.6 on 2025-10-23 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhan_vien', '0002_chucvu_phongban_chamcong_alter_nhanvien_chuc_vu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamcong',
            options={'verbose_name': 'Chấm Công', 'verbose_name_plural': 'Chấm Công'},
        ),
        migrations.AlterModelOptions(
            name='chucvu',
            options={'verbose_name': 'Chức Vụ', 'verbose_name_plural': 'Chức Vụ'},
        ),
        migrations.AlterModelOptions(
            name='donxinnghi',
            options={'verbose_name': 'Đơn Xin Nghỉ', 'verbose_name_plural': 'Đơn Xin Nghỉ'},
        ),
        migrations.AlterModelOptions(
            name='phongban',
            options={'verbose_name': 'Phòng Ban', 'verbose_name_plural': 'Phòng Ban'},
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('Manager', 'Manager'), ('Employee', 'Employee')], default='Employee', max_length=20, verbose_name='Vai trò')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
