# Generated by Django 5.2.7 on 2025-10-24 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhan_vien', '0003_alter_chamcong_options_alter_chucvu_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nhan_vien.nhanvien'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(default='Employee', max_length=50),
        ),
    ]
