# Generated by Django 5.2.6 on 2025-10-24 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhan_vien', '0004_useraccount_employee_alter_useraccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhan_vien.nhanvien'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('Manager', 'Manager'), ('Employee', 'Employee')], default='Employee', max_length=20, verbose_name='Vai trò'),
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang', models.PositiveIntegerField(verbose_name='Tháng')),
                ('nam', models.PositiveIntegerField(verbose_name='Năm')),
                ('luong_co_ban', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Lương cơ bản')),
                ('phu_cap', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Phụ cấp')),
                ('khau_tru', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Khấu trừ')),
                ('luong_thuc_nhan', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Lương thực nhận')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhan_vien.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Bảng Lương',
                'verbose_name_plural': 'Bảng Lương',
                'unique_together': {('nhan_vien', 'thang', 'nam')},
            },
        ),
    ]
